name: cfug_translator_bot
description:
version: 0.0.12

publish_to: none

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  args: 2.7.0
  uuid: 4.5.3
  github: 9.25.1
  http: 1.6.0
  googleai_dart: 8.0.0
  openai_dart: 6.2.0

dev_dependencies:
  lints: any
  test: any